### PR TITLE
Draft editor advice

### PR DESCRIPTION
**Pull request by msdemlei**

### CODE REVIEW

**Comment by mbtaylor** [comment]
I don't consider myself expert on github gymnastics and I haven't tried out the steps in the _Adopting..._ section, but this looks reasonable to me.

**Comment by jd-au** [comment]
The procedure looks sensible to me, pending filling in the couple of TODOs. The _Adopting..._ section could be trialled when moving this repo to ivoa

**Comment by molinaro-m** [comment]
I agree with the above comments. Looks good to be merged. A chance to test the adoption could be this document directly in _ivoa-std_ or, more work, create a test document and work out the adoption into the _ivoa_ organisation, where a template repo is missing.

**Comment by pdowler** [comment]
After a little experimentation, here is a simplification for the migration/transfer process:

\item Create a repository \verb|ivoa-std/<short-name>| via github's
browser UI.  Make sure this repository is public and uses the template _doc-template_
\item Locally clone the freshly created repository: \verb|git clone <repo>|
\item \verb|git pull --allow-unrelated-histories <original-repo> master|
\item \verb|git push origin master|
\item Setup branch protection rules for the _master_ branch
\item Give the WG chair and the editor the following privileges: maintainer role
\item Notify the WG of the move via the WG's mailing list

The ivoa-std maintainer can push directly to the repository before setting up branch protection rules, so no need for a fork and pull request in this case.

A couple of things to iron out:
1. there is a shift from using _master_ to using _main_ so we need to pick one, change existing repos, docs, and habits to match
2. consistent branch protection rules: I can add the details in a separate PR, but it essentially enforces (or not) the PR vs local branch vs push directly to master policy

**Pull request merged**
